### ISSUE TITLE
Add isort and black

### ISSUE THREAD

**Issue by serhii73** [serhii73/ukrdict#16]
Add isort and black to pre-commit

**Comment by webknjaz** [comment]
Anthony has an alternative btw https://twitter.com/codewithanthony/status/1152221594850168832?s=19

**Comment by serhii73** [comment]
Thank you very much, Sviatoslav.

**Comment by serhii73** [comment]
https://github.com/asottile/add-trailing-comma

**Comment by serhii73** [comment]
https://github.com/asottile/reorder_python_imports
