### ISSUE TITLE
Add settings for auto-comment bot

### ISSUE THREAD

**Issue by serhii73** [serhii73/ukrdict#24]
[https://probot.github.io/apps/auto-comment/](https://probot.github.io/apps/auto-comment/) - please, add `./github/auto-comment.yml` to this project.
Thank you very much!

**Comment by undef1nd** [comment]
Hey @serhii73,

What kind of options should be enabled? There's a bunch of them available https://github.com/boyney123/auto-comment

**Comment by serhii73** [comment]
Hello @undef1nd 

I think we can add 
`issuesOpened` and `issuesClosed`
`pullRequestOpened` and `pullRequestClosed`

Complete freedom in what to write in messages on each of these problems. =)

**Comment by undef1nd** [comment]
Cool, will work on this.
