### ISSUE TITLE
Improve current Python code

### ISSUE THREAD

**Issue by serhii73** [serhii73/ukrdict#49]
If you see what can improve in this project please create an issue or send me the PR.
Happy Hacktoberfest!
![Screenshot from 2019-10-08 21-51-56](https://user-images.githubusercontent.com/24910277/66424263-fb217f00-ea15-11e9-9154-10eb99e86484.png)

**Comment by deadpyxel** [comment]
I would like to work on this, but I don't speak ukrainian, is that a problem?

**Comment by serhii73** [comment]
No, it's not a problem if you not know Ukrainian.
Thank you very much!

**Comment by deadpyxel** [comment]
Sure thing. I"ll work on it this week. I see your code looks good, so I think I"ll add some more tests and see if there're any pertinent changes in the structure.
